const INITIAL_TOOL = 'PEN';
const FULL_CANVAS_SIZE = 700;
const INITIAL_CANVAS_SIZE = 32;
const INITIAL_PRIMARY_COLOR = '#000000';
const INITIAL_SECONDARY_COLOR = '#ffffff';
const TRANSPARENT_COLOR = 'rgba(0, 0, 0, 0)';
const INITIAL_FPS = 5;
const EXPORT_FILE_NAME = 'NewPiskelClone';
const SHORTCUTS = {
  PEN: 'P',
  MIRROR_PEN: 'V',
  STROKE: 'L',
  RECTANGLE: 'R',
  CIRCLE: 'C',
  MOVE: 'M',
  ERASER: 'E',
  COLOR_PICKER: 'O',
  DITHERING: 'T',
  LIGHTEN: 'U',
  FULLSCREEN_MODE: 'F',
};

export {
  INITIAL_TOOL,
  FULL_CANVAS_SIZE,
  INITIAL_CANVAS_SIZE,
  INITIAL_PRIMARY_COLOR,
  INITIAL_SECONDARY_COLOR,
  TRANSPARENT_COLOR,
  INITIAL_FPS,
  EXPORT_FILE_NAME,
  SHORTCUTS,
};
