export default {
  PEN: 'PEN',
  MIRROR_PEN: 'MIRROR_PEN',
  STROKE: 'STROKE',
  RECTANGLE: 'RECTANGLE',
  CIRCLE: 'CIRCLE',
  MOVE: 'MOVE',
  ERASER: 'ERASER',
  COLOR_PICKER: 'COLOR_PICKER',
  DITHERING: 'DITHERING',
  LIGHTEN: 'LIGHTEN',
};
